---
abstract: 'Mouse with Singleton Method facility'
author:
  - 'Hideaki Ohno <hide.o.j55 {at} gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MouseX-SingletonMethod
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Mouse: 0
  Mouse::Role: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hideo55/p5-MouseX-SingletonMethod.git
version: 0.02
