---
abstract: 'Mouse with Singleton Method facility'
author:
  - 'Hideaki Ohno<hide.o.j55@gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
keywords:
  - Mouse
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MouseX-SingletonMethod
no_index:
  directory:
    - t
    - xt
    - inc
    - eg
provides:
  MouseX::SingletonMethod:
    file: lib/MouseX/SingletonMethod.pm
    version: 0.03
  MouseX::SingletonMethod::Role:
    file: lib/MouseX/SingletonMethod/Role.pm
    version: 0
requires:
  Mouse: 0
  Mouse::Role: 0
  perl: v5.6.2
resources:
  bugtracker: https://github.com/hideo55/p5-MouseX-SingletonMethod/issues
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hideo55/p5-MouseX-SingletonMethod.git
version: 0.03
